/* ============================================================
   QUIZ QUESTION BANK — 3 levels (easy/medium/hard), 50 har level
   q = sawaal, o = options, a = sahi option ka index, i = jaankari
   Har quiz me 12 random sawaal aate hain (QuizPage shuffle karta hai)
   ============================================================ */
export const QUIZ_BANK = {
  easy: [
    { q: "Krishna ko janm dene wali mata kaun thin?", o: ["Yashoda", "Devki", "Rohini", "Kirti"], a: 1, i: "Devki ji ne Mathura ki jail me Krishna ko janm diya tha." },
    { q: "Krishna ke janm-pita kaun the?", o: ["Nand Baba", "Vasudev", "Ugrasen", "Akrura"], a: 1, i: "Vasudev ji Krishna ke pita the — unhi ne Krishna ko Gokul pahunchaya." },
    { q: "Krishna ko paalne wali maiya kaun thin?", o: ["Devki", "Rohini", "Yashoda", "Putana"], a: 2, i: "Yashoda maiya ne Gokul me Krishna ka palan-poshan kiya." },
    { q: "Krishna kaunsa vadya bajate the?", o: ["Veena", "Basuri", "Mridang", "Shankh"], a: 1, i: "Krishna ki basuri (murli) ki dhun par pura Vrindavan tham jata tha." },
    { q: "Krishna ke mukut me kya sajta hai?", o: ["Mor pankh", "Gulab", "Chandan", "Heera"], a: 0, i: "Mor pankh Krishna ki pehchaan hai — isliye unhe Mor Mukut Dhari kehte hain." },
    { q: "Bachpan me Krishna ko kya churana pasand tha?", o: ["Laddu", "Makhan", "Kheer", "Peda"], a: 1, i: "Makhan chori ki leela ke karan Krishna 'Makhan Chor' kehlaye." },
    { q: "Radha Rani ka gaon kaunsa hai?", o: ["Gokul", "Nandgaon", "Barsana", "Mathura"], a: 2, i: "Barsana Radha Rani ka gaon hai — wahan unka Shriji Mandir hai." },
    { q: "Krishna ka janm kahan hua tha?", o: ["Gokul", "Vrindavan", "Dwarka", "Mathura ki jail me"], a: 3, i: "Kans ki jail me Bhadrapada Krishna Ashtami ko Krishna ka janm hua." },
    { q: "Krishna ka mama kaun tha?", o: ["Kans", "Jarasandh", "Shishupal", "Akrura"], a: 0, i: "Kans Devki ka bhai tha — usi ne dono ko jail me daala tha." },
    { q: "Krishna ne kaunsa parvat ungli par uthaya?", o: ["Kailash", "Govardhan", "Vindhya", "Himalaya"], a: 1, i: "Indra ki varsha se bachane ke liye Krishna ne Govardhan uthaya." },
    { q: "Krishna ke bade bhai kaun the?", o: ["Balram", "Uddhav", "Sudama", "Arjun"], a: 0, i: "Balram (Dau ji) Krishna ke bade bhai the — Rohini ke putra." },
    { q: "Vrindavan kis nadi ke kinare hai?", o: ["Ganga", "Saraswati", "Yamuna", "Narmada"], a: 2, i: "Yamuna ji Vrindavan ki jeevan-rekha hain — Krishna ki leelaon ki saakshi." },
    { q: "Krishna ki behen kaun thin?", o: ["Draupadi", "Subhadra", "Rukmini", "Radha"], a: 1, i: "Subhadra Krishna ki behen thin — Arjun se unka vivah hua." },
    { q: "Janmashtami kiska janmotsav hai?", o: ["Ram", "Krishna", "Balram", "Vishnu"], a: 1, i: "Janmashtami Shri Krishna ka prakatya divas hai." },
    { q: "Radhashtami kiska prakatya divas hai?", o: ["Radha Rani", "Yashoda", "Devki", "Sita"], a: 0, i: "Radhashtami par Barsana me sabse bada utsav hota hai." },
    { q: "Krishna ke saanwle rang ke karan unhe kya kehte hain?", o: ["Gaur", "Shyam", "Neel", "Kanha"], a: 1, i: "Saanwle rang ke karan Krishna ko Shyam ya Ghanshyam kehte hain." },
    { q: "Bhagavad Gita ka updesh kisne diya?", o: ["Ved Vyas", "Krishna", "Balram", "Narad"], a: 1, i: "Kurukshetra ke maidan me Krishna ne Arjun ko Gita sunayi." },
    { q: "Gita ka updesh kise mila?", o: ["Bheem", "Yudhishthir", "Arjun", "Karna"], a: 2, i: "Arjun ke moh ko door karne ke liye Krishna ne Gita kahi." },
    { q: "Gita ka updesh kahan diya gaya?", o: ["Mathura", "Hastinapur", "Kurukshetra", "Indraprastha"], a: 2, i: "Mahabharat yuddh se pehle Kurukshetra me Gita ka updesh hua." },
    { q: "Lathmar Holi kahan famous hai?", o: ["Barsana", "Jaipur", "Kashi", "Ayodhya"], a: 0, i: "Barsana ki Lathmar Holi me sakhiyan gwalon ko laathi maarti hain." },
    { q: "Banke Bihari Mandir kahan hai?", o: ["Mathura", "Vrindavan", "Barsana", "Gokul"], a: 1, i: "Banke Bihari ji Vrindavan ke sabse prasiddh Thakur hain." },
    { q: "Krishna Vrindavan me kya charate the?", o: ["Bhains", "Bakri", "Gaay", "Ghode"], a: 2, i: "Krishna gwala the — gaiya charana unki nitya leela thi." },
    { q: "Kaliya kaun tha?", o: ["Rakshas", "Zehrila naag", "Asur raja", "Magarmach"], a: 1, i: "Kaliya naag ke zeher se Yamuna ka paani vish ban gaya tha." },
    { q: "Kaliya naag kahan rehta tha?", o: ["Ganga me", "Yamuna me", "Samudra me", "Kund me"], a: 1, i: "Krishna ne Yamuna me kood kar Kaliya ka maan mardan kiya." },
    { q: "Dahi Handi kis tyohar par hoti hai?", o: ["Holi", "Diwali", "Janmashtami", "Teej"], a: 2, i: "Janmashtami par makhan-dahi ki matki phodne ki parampara hai." },
    { q: "'Radhe Radhe' kahan ka abhivadan hai?", o: ["Braj", "Punjab", "Bengal", "Kashi"], a: 0, i: "Braj me namaste ki jagah 'Radhe Radhe' bola jata hai." },
    { q: "Hare Krishna movement videsh tak kisne pahunchaya?", o: ["Vivekananda", "Srila Prabhupada", "Ramdev", "Shankaracharya"], a: 1, i: "Srila Prabhupada ne 1966 me New York me ISKCON ki sthapna ki." },
    { q: "Krishna ki sabse priya kaun hain?", o: ["Rukmini", "Satyabhama", "Radha", "Lalita"], a: 2, i: "Radha Krishna ka prem bhakti ka sarvochh roop mana jata hai." },
    { q: "Raas Leela me Krishna kiske saath nachte the?", o: ["Gopiyan", "Devta", "Sakha", "Apsara"], a: 0, i: "Sharad Purnima ki raat har gopi ke saath ek Krishna the." },
    { q: "Krishna ka chakra kaunsa hai?", o: ["Kaal chakra", "Sudarshan chakra", "Dharma chakra", "Agni chakra"], a: 1, i: "Sudarshan chakra Krishna ki tarjani par ghoomta hai." },
    { q: "Krishna badi umar me kis nagri ke raja bane?", o: ["Mathura", "Hastinapur", "Dwarka", "Magadh"], a: 2, i: "Samudra kinare basi Dwarka Krishna ne basayi thi." },
    { q: "Sudama kaun the?", o: ["Krishna ke mitra", "Krishna ke bhai", "Ek rishi", "Ek raja"], a: 0, i: "Gareeb brahman Sudama Krishna ke bachpan ke mitra the." },
    { q: "Sudama Krishna ke liye kya laye the?", o: ["Makhan", "Chawal (poha)", "Phal", "Mithai"], a: 1, i: "Sudama ke kacche chawal Krishna ne prem se khaye aur unhe sab kuch de diya." },
    { q: "Krishna ne Draupadi ki laaj kaise bachai?", o: ["Yuddh karke", "Sari badha ke", "Sabha rok ke", "Shraap dekar"], a: 1, i: "Cheer-haran ke samay Krishna ne Draupadi ki sari anant kar di." },
    { q: "'Makhan Chor' kise kehte hain?", o: ["Balram", "Krishna", "Sudama", "Madhumangal"], a: 1, i: "Gokul ki gopiyon ka makhan churane ke karan Krishna Makhan Chor kehlaye." },
    { q: "Prem Mandir kahan hai?", o: ["Barsana", "Mathura", "Vrindavan", "Govardhan"], a: 2, i: "Safed marble ka Prem Mandir Vrindavan ki shaan hai." },
    { q: "Govardhan Parikrama kaise karne ki parampara hai?", o: ["Gadi se", "Nange paon paidal", "Ghode par", "Naav se"], a: 1, i: "21 km ki parikrama nange paon karne ki parampara hai." },
    { q: "Radha-Krishna ke jhoolan ka utsav kis mahine me hota hai?", o: ["Kartik", "Sawan", "Chaitra", "Magh"], a: 1, i: "Sawan me Hariyali Teej par Thakur ji ko jhoola jhulaya jata hai." },
    { q: "Yashoda ne Krishna ke mukh me kya dekha tha?", o: ["Makhan", "Mitti", "Pura brahmand", "Kuch nahi"], a: 2, i: "Mitti khane par muh khulwaya to Yashoda ko brahmand ke darshan hue." },
    { q: "Krishna ka bachpan kahan beeta?", o: ["Mathura me", "Gokul-Vrindavan me", "Dwarka me", "Hastinapur me"], a: 1, i: "Janm Mathura me hua par bachpan ki leelayein Gokul-Vrindavan me huin." },
    { q: "Holi kis mausam ka tyohar hai?", o: ["Basant", "Varsha", "Sharad", "Shishir"], a: 0, i: "Phagun me basant ke rang ke saath Holi aati hai." },
    { q: "Janm ke turant baad Krishna ko kahan le jaya gaya?", o: ["Vrindavan", "Gokul", "Nandgaon", "Barsana"], a: 1, i: "Vasudev ji Yamuna paar karke Krishna ko Nand Baba ke ghar Gokul le gaye." },
    { q: "Yamuna paar karte samay Krishna ko baarish se kisne bachaya?", o: ["Garud", "Shesh Naag", "Hanuman", "Indra"], a: 1, i: "Shesh Naag ne apne phan ka chhata bana ke Krishna ko bachaya." },
    { q: "Krishna ki basuri sunke kaun mantra-mugdh ho jata tha?", o: ["Sirf gopiyan", "Sirf gaay", "Sab — gopi, gaay, panchhi", "Sirf sakha"], a: 2, i: "Basuri ki dhun par pashu-panchhi, ped-paudhe sab tham jate the." },
    { q: "Krishna ki pooja me kaunsa patta zaroori mana jata hai?", o: ["Bel patra", "Tulsi", "Peepal", "Aam ka patta"], a: 1, i: "Tulsi dal ke bina Krishna ka bhog adhura mana jata hai." },
    { q: "Mathura ki famous mithai kaunsi hai?", o: ["Rasgulla", "Peda", "Jalebi", "Barfi"], a: 1, i: "Mathura ke pede ka bhog Thakur ji ko lagta hai." },
    { q: "Krishna ko 'Girdhari' kyun kehte hain?", o: ["Giri (parvat) dharan kiya", "Gir van me rehte the", "Giri naam ka asur mara", "Gida bajate the"], a: 0, i: "Govardhan giri ko dharan karne se Krishna Girdhari kehlaye." },
    { q: "Kans ka vadh kisne kiya?", o: ["Balram", "Krishna", "Vasudev", "Ugrasen"], a: 1, i: "Mathura ke akhade me Krishna ne atyachari Kans ka vadh kiya." },
    { q: "Bhagavad Gita kis granth ka hissa hai?", o: ["Ramayan", "Mahabharat", "Ved", "Puran"], a: 1, i: "Gita Mahabharat ke Bheeshma Parva ka amar hissa hai." },
    { q: "Krishna ko pyar se Braj me kya bulate hain?", o: ["Kanha", "Mohan", "Lala", "Ye sabhi"], a: 3, i: "Kanha, Mohan, Lala, Gopal — Braj me Krishna ke anek pyare naam hain." },
  ],
  medium: [
    { q: "Radha Rani ke pita ka naam kya tha?", o: ["Nand Baba", "Vrishbhanu", "Vasudev", "Ugrasen"], a: 1, i: "Vrishbhanu ji Barsana ke raja the." },
    { q: "Radha Rani ki mata kaun thin?", o: ["Yashoda", "Rohini", "Kirti", "Devki"], a: 2, i: "Kirti (Kirtida) ji Radha Rani ki mata thin — Barsana me Kirti Mandir unhi ka hai." },
    { q: "Balram ki mata kaun thin?", o: ["Devki", "Yashoda", "Rohini", "Kirti"], a: 2, i: "Rohini ji Vasudev ki patni thin — Balram unke putra hain." },
    { q: "Putana kaun thi?", o: ["Gopi", "Zeher pilane aayi rakshasi", "Kans ki behen", "Daasi"], a: 1, i: "Kans ki bheji Putana zeher lagakar dudh pilane aayi thi." },
    { q: "Krishna ke guru kaun the?", o: ["Vashishth", "Sandipani Muni", "Vishwamitra", "Drona"], a: 1, i: "Krishna-Balram ne Sandipani Muni ke ashram me 64 kalayein seekhin." },
    { q: "Sandipani Muni ka ashram kahan tha?", o: ["Kashi", "Ujjain", "Haridwar", "Prayag"], a: 1, i: "Ujjain (Avantika) me Sandipani ashram aaj bhi hai." },
    { q: "Kans ke pita kaun the?", o: ["Jarasandh", "Ugrasen", "Shurasen", "Devak"], a: 1, i: "Kans ne apne hi pita Ugrasen ko gaddi se hata diya tha." },
    { q: "Krishna-Balram ko Mathura bulane kaun aaya tha?", o: ["Uddhav", "Akrura", "Narad", "Kans khud"], a: 1, i: "Akrura ji Kans ka nyota lekar Vrindavan aaye the." },
    { q: "Krishna ne gopiyon ko samjhane kise Vrindavan bheja?", o: ["Balram", "Uddhav", "Akrura", "Sudama"], a: 1, i: "Uddhav gyan lekar gaye par gopiyon ka prem dekh khud badal gaye." },
    { q: "Krishna ki pehli pattrani kaun thin?", o: ["Satyabhama", "Rukmini", "Jambavati", "Kalindi"], a: 1, i: "Rukmini ji ko Krishna swayam har kar laye the." },
    { q: "Krishna ke shankh ka naam kya hai?", o: ["Devdutt", "Panchajanya", "Anantvijay", "Paundra"], a: 1, i: "Panchajanya shankh ki dhwani se yuddh ka aarambh hota tha." },
    { q: "Bhagavad Gita me kitne adhyay hain?", o: ["12", "16", "18", "24"], a: 2, i: "Gita ke 18 adhyay me karm, bhakti aur gyan yog ka saar hai." },
    { q: "Chhappan bhog me kitne vyanjan hote hain?", o: ["21", "36", "56", "108"], a: 2, i: "Govardhan leela ke baad 7 din × 8 pehar = 56 bhog ki parampara bani." },
    { q: "56 bhog ki ginti kaise aayi?", o: ["7 din × 8 pehar", "8 din × 7 pehar", "56 gopiyan", "56 gaon"], a: 0, i: "Krishna 7 din bina khaye Govardhan uthaye rahe — har din ke 8 pehar ka bhog." },
    { q: "Banke Bihari ji ko kisne prakat kiya?", o: ["Surdas", "Swami Haridas", "Vallabhacharya", "Meerabai"], a: 1, i: "Swami Haridas ji ki bhakti se Nidhivan me Bihari ji prakat hue." },
    { q: "Swami Haridas kiske guru the?", o: ["Baiju Bawra", "Tansen", "Surdas", "Kabir"], a: 1, i: "Sangeet samrat Tansen Swami Haridas ke shishya the." },
    { q: "Radha Raman Mandir ke sansthapak kaun the?", o: ["Rupa Goswami", "Gopala Bhatta Goswami", "Jiva Goswami", "Sanatana Goswami"], a: 1, i: "1542 me shaligram se Radha Raman ji swayam prakat hue." },
    { q: "Prem Mandir kisne banwaya?", o: ["Prabhupada", "Kripalu Ji Maharaj", "Birla parivar", "Ramanujacharya"], a: 1, i: "Jagadguru Kripalu Ji Maharaj ne 2012 me Prem Mandir banwaya." },
    { q: "ISKCON ki sthapna kis saal hui?", o: ["1947", "1966", "1975", "1980"], a: 1, i: "1966 me New York me Srila Prabhupada ne ISKCON shuru kiya." },
    { q: "ISKCON Vrindavan ke mandir ka naam kya hai?", o: ["Radha Raman", "Krishna Balaram Mandir", "Govind Dev", "Rang Ji"], a: 1, i: "1975 me bana Krishna Balaram Mandir ISKCON ka pramukh mandir hai." },
    { q: "Govardhan Parikrama kitne km ki hai?", o: ["11 km", "15 km", "21 km", "31 km"], a: 2, i: "Poori parikrama 21 km hai — Radha Kund aur Mansi Ganga bhi raste me aate hain." },
    { q: "Radhashtami Janmashtami ke kitne din baad aati hai?", o: ["7 din", "15 din", "21 din", "30 din"], a: 1, i: "Krishna janm ke 15 din baad Radha Rani ka prakatya hua." },
    { q: "Nidhivan ke tulsi ke pedon ki kya khaas baat hai?", o: ["Sab akele hain", "Jode me hain", "Sookhe hain", "Sone jaise hain"], a: 1, i: "Manyata hai ki jode wale tulsi ped raas ki gopiyan hain." },
    { q: "Radha Rani ki ashtasakhi kitni hain?", o: ["4", "8", "12", "16"], a: 1, i: "Lalita, Vishakha samet 8 pramukh sakhiyan ashtasakhi kehlati hain." },
    { q: "Radha ji ki sabse pramukh sakhi kaun?", o: ["Chandravali", "Lalita", "Kubja", "Trivakra"], a: 1, i: "Lalita sakhi ashtasakhiyon me pramukh hain." },
    { q: "Krishna ne Kaliya ko kahan jaane ko kaha?", o: ["Patal lok", "Ramanak dweep", "Samudra", "Ganga"], a: 1, i: "Kaliya apne parivar sang Ramanak dweep chala gaya." },
    { q: "Kans ke vadh ke baad Mathura ki gaddi kise mili?", o: ["Krishna", "Balram", "Ugrasen", "Vasudev"], a: 2, i: "Krishna ne khud raja na ban kar Ugrasen ko gaddi wapas di." },
    { q: "Jarasandh kaun tha?", o: ["Kans ka sasur", "Kans ka bhai", "Kans ka mantri", "Kans ka guru"], a: 0, i: "Magadh naresh Jarasandh ki betiyan Kans se byahi thin — usne Mathura par 17 baar chadhai ki." },
    { q: "Krishna Mathura chhod kar kahan ja base?", o: ["Hastinapur", "Dwarka", "Ujjain", "Indraprastha"], a: 1, i: "Jarasandh ke baar-baar aakraman ke karan Krishna Dwarka ja base — isliye 'Ranchhod' bhi kehlaye." },
    { q: "Dwarka kis aaj ke rajya me hai?", o: ["Maharashtra", "Rajasthan", "Gujarat", "Goa"], a: 2, i: "Dwarkadhish mandir Gujarat ke samudra tat par hai." },
    { q: "Shrinathji ka pramukh mandir kahan hai?", o: ["Vrindavan", "Nathdwara", "Dwarka", "Jagannath Puri"], a: 1, i: "Govardhan se prakat Shrinathji ab Rajasthan ke Nathdwara me virajman hain." },
    { q: "Shrinathji kis parvat se prakat hue the?", o: ["Barsana pahadi", "Govardhan", "Nandgaon pahadi", "Kailash"], a: 1, i: "Shrinathji Govardhan parvat se prakat hue — Pushtimarg ke aradhya." },
    { q: "Dauji Mandir kiska mandir hai?", o: ["Krishna", "Balram", "Nand Baba", "Uddhav"], a: 1, i: "Baldeo (Mathura ke paas) ka Dauji mandir Balram ji ka pramukh mandir hai." },
    { q: "Huranga Holi kahan kheli jati hai?", o: ["Barsana", "Nandgaon", "Dauji (Baldeo)", "Gokul"], a: 2, i: "Dauji mandir ka Huranga Holi ke baad ka anokha utsav hai." },
    { q: "Braj me kitne van (forest) mane gaye hain?", o: ["7", "12", "24", "84"], a: 1, i: "Madhuvan, Talvan, Kumudvan jaise 12 van Braj ki parikrama me aate hain." },
    { q: "Barsana ka purana naam kya tha?", o: ["Radhapur", "Vrishbhanupur", "Kirtigram", "Shripuri"], a: 1, i: "Raja Vrishbhanu ke naam par Barsana Vrishbhanupur kehlata tha." },
    { q: "Radha Kund ke theek saath kaunsa kund hai?", o: ["Prem Kund", "Shyam Kund", "Lalita Kund", "Mansi Kund"], a: 1, i: "Radha Kund aur Shyam Kund jode me hain — dono ki parikrama hoti hai." },
    { q: "Kesi Ghat ka naam kis par pada?", o: ["Kesi rishi", "Keshi rakshas", "Kesar", "Keshav"], a: 1, i: "Krishna ne ghode ka roop dhare Keshi rakshas ka vadh yahin kiya tha." },
    { q: "Vishram Ghat kyun prasiddh hai?", o: ["Krishna ne yahan vishram kiya", "Yamuna yahan rukti hai", "Rishi yahan sote the", "Kans yahan baitha tha"], a: 0, i: "Kans vadh ke baad Krishna-Balram ne yahin vishram kiya tha." },
    { q: "Sharad Purnima ko kheer chandni me kyun rakhte hain?", o: ["Thandi karne", "Amrit varsha ki manyata", "Chandrama ko bhog", "Parampara bhar"], a: 1, i: "Manyata hai ki Sharad Purnima ki chandni se amrit barasta hai." },
    { q: "Shrimad Bhagavata Purana me kitne skandh hain?", o: ["10", "12", "18", "24"], a: 1, i: "Bhagavatam ke 12 skandh hain — bhakti ka mahasagar." },
    { q: "Krishna leela Bhagavatam ke kis skandh me hai?", o: ["Pancham", "Saptam", "Dasham", "Dwadash"], a: 2, i: "Dasham skandh (10th canto) me Krishna ki leelayein hain." },
    { q: "Chaitanya Mahaprabhu ka janm kahan hua?", o: ["Vrindavan", "Mayapur (Bengal)", "Puri", "Kashi"], a: 1, i: "1486 me Mayapur me janme Chaitanya Mahaprabhu ne sankirtan phailaya." },
    { q: "'Tribhanga' mudra ka kya matlab hai?", o: ["Teen haath", "Teen jagah se mudi mudra", "Teen aankhein", "Teen kadam"], a: 1, i: "Krishna ki khadi mudra teen jagah se mudti hai — isi se 'Banke' bane." },
    { q: "Seva Kunj (Vrindavan) kis leela se juda hai?", o: ["Makhan chori", "Nikunj leela", "Govardhan leela", "Kaliya mardan"], a: 1, i: "Seva Kunj me Krishna Radha Rani ki seva-shringar karte hain — raat ko band rehta hai." },
    { q: "Gopashtami kya yaad dilati hai?", o: ["Gopiyon ka janm", "Krishna ka gau charana shuru karna", "Gokul chhodna", "Gopal naam padna"], a: 1, i: "Gopashtami se Krishna ne gaay charana shuru kiya tha." },
    { q: "Yamuna ji ka doosra naam kya hai?", o: ["Bhagirathi", "Kalindi", "Mandakini", "Alaknanda"], a: 1, i: "Kalind parvat se nikalne ke karan Yamuna Kalindi kehlati hain." },
    { q: "Krishna ki kitni pattraniyan (pramukh raniyan) thin?", o: ["2", "4", "8", "16"], a: 2, i: "Rukmini, Satyabhama, Jambavati samet 8 pattraniyan thin." },
    { q: "Mor Kutir kahan hai?", o: ["Vrindavan", "Barsana", "Gokul", "Govardhan"], a: 1, i: "Barsana ke Mor Kutir me Krishna ne mor ban kar Radha ko rijhaya tha." },
    { q: "Phoolon wali Holi kis mandir me hoti hai?", o: ["Prem Mandir", "Banke Bihari", "Dwarkadhish", "Radha Raman"], a: 1, i: "Banke Bihari mandir me Ekadashi par phoolon ki Holi hoti hai." },
  ],
  hard: [
    { q: "Manyata anusaar Radha Rani ka janm kis gaon me hua tha?", o: ["Barsana", "Rawal", "Nandgaon", "Gokul"], a: 1, i: "Rawal (Yamuna paar) Radha ji ki janmasthali hai — baad me parivar Barsana aa gaya." },
    { q: "Dwarka me Krishna ke rath ke sarathi kaun the?", o: ["Daruka", "Satyaki", "Uddhav", "Pradyumna"], a: 0, i: "Daruka Krishna ke vishwasniya sarathi the." },
    { q: "Krishna ki talwar ka naam kya hai?", o: ["Chandrahas", "Nandak", "Asi", "Khadga"], a: 1, i: "Nandak Krishna ki divya talwar hai." },
    { q: "Krishna ke dhanush ka naam kya hai?", o: ["Gandiv", "Pinak", "Sharang", "Vijay"], a: 2, i: "Sharang dhanush Vishnu-Krishna ka divya dhanush hai." },
    { q: "Krishna ki gada ka naam kya hai?", o: ["Kaumodaki", "Gada-Vajra", "Saunanda", "Shatnik"], a: 0, i: "Kaumodaki gada Krishna ke chaturbhuj roop me sushobhit hai." },
    { q: "Inme se Krishna ke rath ka ghoda kaunsa hai?", o: ["Chetak", "Shaibya", "Kanthak", "Uchchaihshrava"], a: 1, i: "Shaibya, Sugriv, Meghpushp aur Balahak — Krishna ke 4 ghode." },
    { q: "Bhagavad Gita me kul kitne shlok hain?", o: ["500", "600", "700", "1000"], a: 2, i: "Gita ke 700 shlok 18 adhyayon me bate hain." },
    { q: "Syamantak mani ki katha me Krishna par kya aarop laga?", o: ["Jhooth ka", "Chori ka", "Kapat ka", "Shraap ka"], a: 1, i: "Syamantak mani churane ka jhootha aarop laga — isi se Ganesh Chaturthi chandra-darshan ka dosh juda hai." },
    { q: "Parijat vriksha Krishna kahan se laye the?", o: ["Himalaya", "Swarg (Indra se)", "Lanka", "Patal"], a: 1, i: "Satyabhama ke liye Krishna swarg se Parijat le aaye the." },
    { q: "Lalita ke baad doosri pramukh ashtasakhi kaun?", o: ["Champaklata", "Vishakha", "Chitra", "Indulekha"], a: 1, i: "Vishakha sakhi Radha-Krishna ke sandesh aadan-pradan karti thin." },
    { q: "Inme se do pramukh Goswami (6 Goswamis me se) kaun?", o: ["Rupa-Sanatana", "Tulsidas-Surdas", "Nimbark-Vallabh", "Haridas-Hariram"], a: 0, i: "Rupa aur Sanatana Goswami Chaitanya Mahaprabhu ke aadesh par Vrindavan aaye." },
    { q: "Jiva Goswami kis mandir se jude hain?", o: ["Govind Dev", "Radha Damodar", "Madan Mohan", "Gopinath"], a: 1, i: "Radha Damodar mandir me Jiva Goswami ki gaddi hai." },
    { q: "Radha Vallabh sampradaya ke pravartak kaun?", o: ["Hita Harivansh", "Nimbarkacharya", "Vallabhacharya", "Ramanand"], a: 0, i: "Hita Harivansh Mahaprabhu ne Radha Vallabh mandir ki neev rakhi." },
    { q: "Pushtimarg kis acharya ne chalaya?", o: ["Madhvacharya", "Vallabhacharya", "Ramanujacharya", "Shankaracharya"], a: 1, i: "Vallabhacharya ji ka Pushtimarg — Shrinathji unke aradhya." },
    { q: "Nimbarka sampradaya kiski upasana karta hai?", o: ["Sirf Krishna", "Radha-Krishna yugal", "Vishnu-Lakshmi", "Sirf Radha"], a: 1, i: "Nimbarka sampradaya me yugal sarkar ki upasana sarvopari hai." },
    { q: "Braj 84 kos parikrama kitne km ki hoti hai (approx)?", o: ["84 km", "150 km", "268 km", "500 km"], a: 2, i: "84 kos = approx 268 km — poore Braj mandal ki parikrama." },
    { q: "Kusum Sarovar kis se juda sthal hai?", o: ["Radha ke phool chunne se", "Kans se", "Yamuna se", "Kaliya se"], a: 0, i: "Govardhan ke paas Kusum Sarovar me Radha ji phool chunti thin." },
    { q: "Radha Kund me snan ki sabse badi tithi kaunsi hai?", o: ["Sharad Purnima", "Bahulashtami (Ahoi)", "Radhashtami", "Diwali"], a: 1, i: "Kartik Krishna Ashtami (Ahoi/Bahulashtami) ki madhya-raatri snan ka mahatva hai." },
    { q: "Janmashtami kis tithi ko aati hai?", o: ["Bhadrapada Shukla Ashtami", "Bhadrapada Krishna Ashtami", "Shravan Purnima", "Kartik Ashtami"], a: 1, i: "Bhadrapada maas ke Krishna paksha ki Ashtami — Rohini nakshatra me janm." },
    { q: "Radhashtami kis tithi ko hoti hai?", o: ["Bhadrapada Krishna Ashtami", "Bhadrapada Shukla Ashtami", "Ashwin Ashtami", "Shravan Ashtami"], a: 1, i: "Bhadrapada Shukla Ashtami ko Radha Rani ka prakatya hua." },
    { q: "Holika Dahan kis tithi ko hota hai?", o: ["Phalgun Amavasya", "Phalgun Purnima", "Chaitra Pratipada", "Phalgun Ashtami"], a: 1, i: "Phalgun Purnima ki raat Holika Dahan, agle din Rangwali Holi." },
    { q: "Govardhan Puja kis tithi ko hoti hai?", o: ["Kartik Amavasya", "Kartik Shukla Pratipada", "Kartik Purnima", "Ashwin Pratipada"], a: 1, i: "Diwali ke agle din — Kartik Shukla Pratipada ko Annakoot hota hai." },
    { q: "Sharad Purnima kis mahine ki purnima hai?", o: ["Bhadrapada", "Ashwin", "Kartik", "Margashirsha"], a: 1, i: "Ashwin Purnima hi Sharad Purnima hai — Maha Raas ki raat." },
    { q: "Dev Deepawali kab manai jati hai?", o: ["Diwali par", "Kartik Purnima par", "Sharad Purnima par", "Makar Sankranti par"], a: 1, i: "Kartik Purnima par ghat-ghat diye jalte hain." },
    { q: "Chaitanya Mahaprabhu Vrindavan me kis ped ke neeche baithte the?", o: ["Kadamb Tala", "Imli Tala", "Vat Vriksha", "Peepal Tala"], a: 1, i: "Imli Tala par japte-japte unka gaur varn shyam ho jata tha — manyata." },
    { q: "Bhramar Geet kis prasang se juda hai?", o: ["Raas leela", "Uddhav-gopi samvad", "Govardhan", "Mathura gaman"], a: 1, i: "Gopiyon ne bhanware ke bahane Uddhav ko prem ka paath padhaya." },
    { q: "Gopiyon ne Uddhav ko kya sikhaya?", o: ["Yog shreshtha hai", "Prem gyan se bada hai", "Tyag zaroori hai", "Moksha hi lakshya hai"], a: 1, i: "Nirgun gyan lekar aaye Uddhav prem-bhakti ke aage nat-mastak ho gaye." },
    { q: "Krishna ne Govardhan kis ungli par uthaya tha?", o: ["Angutha", "Tarjani", "Madhyama", "Kanishtha (chhoti)"], a: 3, i: "Sabse chhoti ungli (kanishtha) par 7 din parvat uthaye rakha." },
    { q: "Guru-dakshina me Sandipani Muni ne kya manga?", o: ["Dhan", "Rajya", "Apna mrit putra wapas", "Ashram"], a: 2, i: "Krishna-Balram Yamraj se guru-putra ko wapas le aaye." },
    { q: "Keshi rakshas kis roop me aaya tha?", o: ["Bail", "Ghoda", "Ajgar", "Bagula"], a: 1, i: "Vishal ghode ke roop me aaye Keshi ka Krishna ne vadh kiya — isi se Keshav naam." },
    { q: "Bakasur kis roop me aaya tha?", o: ["Bagula", "Kauwa", "Gidh", "Baaz"], a: 0, i: "Vishal bagule ke roop me Bakasur ne Krishna ko nigla, par mara gaya." },
    { q: "Aghasur kis roop me aaya tha?", o: ["Sher", "Ajgar", "Bhalu", "Magarmach"], a: 1, i: "Aghasur vishal ajgar ban kar raste me muh khole leta tha." },
    { q: "Trinavart kaun sa roop lekar aaya?", o: ["Aandhi/bavandar", "Baarish", "Aag", "Bijli"], a: 0, i: "Bavandar ban kar Krishna ko uda le gaya, par khud mara gaya." },
    { q: "Pralambasur ka vadh kisne kiya?", o: ["Krishna", "Balram", "Nand Baba", "Arjun"], a: 1, i: "Balram ne apni mushti ke prahar se Pralambasur ko mara." },
    { q: "Dwarka nagri ki rachna kisne ki thi?", o: ["Maya danav", "Vishwakarma", "Tvashta", "Ravan"], a: 1, i: "Devshilpi Vishwakarma ne samudra ke beech Dwarka basai." },
    { q: "Braj ke 12 vano me se ek kaunsa hai?", o: ["Madhuvan", "Dandakvan", "Naimisharanya", "Chitrakoot"], a: 0, i: "Madhuvan, Talvan, Kumudvan, Bahulavan... 12 van Braj me hain." },
    { q: "Gokul kis van ke paas basa hai?", o: ["Madhuvan", "Mahavan", "Talvan", "Kamvan"], a: 1, i: "Mahavan-Gokul me Krishna ka palna jhoola tha." },
    { q: "Vrinda devi kaun hain jinke naam par Vrindavan hai?", o: ["Ek gopi", "Tulsi swaroopa devi", "Ek nadi", "Radha ki sakhi"], a: 1, i: "Vrinda (Tulsi) devi ke van ke karan Vrindavan naam pada." },
    { q: "'Shriji' kise kaha jata hai?", o: ["Krishna", "Radha Rani", "Lakshmi", "Yashoda"], a: 1, i: "Barsana ka Shriji Mandir Radha Rani ka hai — 'Shriji' unka aadar naam." },
    { q: "'Banke' Bihari me 'Banke' ka arth kya hai?", o: ["Sundar", "Teen jagah se muda", "Natkhat", "Shyam rang"], a: 1, i: "Tribhanga mudra — teen jagah se banki — isliye Banke Bihari." },
    { q: "Sankari Khor kis leela ka sthal hai?", o: ["Raas leela", "Daan leela", "Maan leela", "Phool leela"], a: 1, i: "Barsana-Nandgaon ke beech tang ghati me Krishna daan mangte the." },
    { q: "Tatiya Sthan kahan hai?", o: ["Barsana", "Vrindavan", "Gokul", "Mathura"], a: 1, i: "Vrindavan ka shant Tatiya Sthan Swami Haridas parampara ka sthal hai." },
    { q: "Bhagavatam me Govardhan ko kya kaha gaya hai?", o: ["Girivar", "Haridasvarya", "Annakoot", "Shailraj"], a: 1, i: "'Haridasvarya' — Hari ke sevakon me shreshtha." },
    { q: "Chhadi Mar Holi kahan hoti hai?", o: ["Barsana", "Nandgaon", "Gokul", "Mathura"], a: 2, i: "Gokul me bal-Krishna ko dhyan me rakh kar laathi ki jagah chhadi se Holi hoti hai." },
    { q: "Krishna ka janm kis nakshatra me hua?", o: ["Ashwini", "Rohini", "Swati", "Revati"], a: 1, i: "Rohini nakshatra me janm — isliye ISKCON me Rohini yukt Ashtami ko utsav hota hai." },
    { q: "'Radha' naam ko ulta padhne par kya banta hai?", o: ["Dhara", "Radha hi", "Haar", "Dhaam"], a: 0, i: "रा-धा ulta ho kar धा-रा — prem ki akhand dhara!" },
    { q: "Ranchhod naam Krishna ko kyun mila?", o: ["Ran me haar gaye", "Yuddh bhoomi chhod di", "Ran jeet liya", "Ran me chhupe"], a: 1, i: "Jarasandh se praja ko bachane ke liye yuddh chhod Dwarka gaye — bhakton ke liye ye tyag hai." },
    { q: "Uddhav ji ko Krishna ne antim updesh kahan diya?", o: ["Dwarka me (Uddhav Gita)", "Mathura me", "Kurukshetra me", "Vrindavan me"], a: 0, i: "Bhagavatam ke 11ve skandh ka 'Uddhav Gita' Krishna ka antim updesh hai." },
    { q: "Dhenukasur kis roop me tha aur kisne mara?", o: ["Gadha — Balram ne", "Bail — Krishna ne", "Ghoda — Krishna ne", "Haathi — Balram ne"], a: 0, i: "Talvan me gadhe ke roop wale Dhenukasur ko Balram ne mara." },
    { q: "Govind Dev Mandir (Vrindavan) kisne banwaya tha?", o: ["Raja Man Singh", "Akbar", "Raja Veer Singh", "Jai Singh"], a: 0, i: "1590 me Amber ke Raja Man Singh ne 7 manzila Govind Dev mandir banwaya." },
  ],
};
